version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: assignment_4/Module_4/docs/source/conf.py

python:
  install:
    - requirements: assignment_4/Module_4/requirements.txt
